apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-06-24T05:50:59Z"
  generateName: busybox-6cf8756958-
  labels:
    app: busybox
    pod-template-hash: 6cf8756958
  name: busybox-6cf8756958-4hsv2
  namespace: demo
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: busybox-6cf8756958
    uid: 2d0eef41-d5d4-4ade-8f27-54e1c071d1db
  resourceVersion: "157231"
  uid: 0fdd707d-6fcc-4e51-a81e-d77448204feb
spec:
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qchh9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: demo-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-qchh9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-06-24T05:50:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-06-24T06:48:48Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-06-24T06:48:48Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-06-24T05:50:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://1a2cb542a8b277ed53da0da45158e307ae9de443d3cd81d91ee90f0ba4fbd86f
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:930490f97e5b921535c153e0e7110d251134cc4b72bbb8133c6a5065cc68580d
    lastState:
      terminated:
        containerID: containerd://1a2cb542a8b277ed53da0da45158e307ae9de443d3cd81d91ee90f0ba4fbd86f
        exitCode: 0
        finishedAt: "2021-06-24T06:53:58Z"
        reason: Completed
        startedAt: "2021-06-24T06:53:58Z"
    name: busybox
    ready: false
    restartCount: 17
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=busybox pod=busybox-6cf8756958-4hsv2_demo(0fdd707d-6fcc-4e51-a81e-d77448204feb)
        reason: CrashLoopBackOff
  hostIP: 172.18.0.2
  phase: Running
  podIP: 10.244.0.28
  podIPs:
  - ip: 10.244.0.28
  qosClass: BestEffort
  startTime: "2021-06-24T05:50:59Z"
